### ISSUE TITLE
Can't NPM install 1.3.0

### ISSUE THREAD

**Issue by Smithx10** [joyent/node-sdc-changefeed#10]
[root@bfae0b60-07d2-42a6-f701-cb30c5aa82b2 /git/cf-test]# npm install --save changefeed@1.3.0
npm ERR! Error while executing:
npm ERR! /opt/local/bin/git ls-remote -h -t ssh://git@github.com/joyent/node-moray.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by melloc** [comment]
@Smithx10 This was fixed in 1.4.0, as part of #7. If you use a newer version of changefeed, you should be all set.
